version: '3.8'

services:
  ghostllm:
    build: .
    container_name: ghostllm
    ports:
      - "8080:8080"
    environment:
      - GHOSTLLM_MODE=serve
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ghostllm-net

  # Optional: Ollama for local LLM inference
  ollama:
    image: ollama/ollama:latest
    container_name: ghostllm-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    networks:
      - ghostllm-net
    # Uncomment for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  ollama-data:

networks:
  ghostllm-net:
    driver: bridge